### ISSUE TITLE
Why do all methods of Headers return a copy?

### ISSUE THREAD

**Issue by KalitaAlexey** [ByteHeathen/libsip#10]
Why not have `from` -> `Option<&Header>` and `from_mut` -> `Option<&mut Header>`.
For my project it doesn't matter, but some people who favor efficiency may not like it.

**Comment by bytebuddha** [comment]
That is essentially a hold over from a much earlier version that wasn't changed because in the app i used to write this library it wasn't required i always needed a cloned instance. But i would be open to changing it since we could simply clone the message

**Comment by KalitaAlexey** [comment]
I could open a pull request to change all methods of `Headers` to have `Option<&Header>` and `Option<&mut Header` versions.
Are you open to that?
