### ISSUE TITLE
server-side SIP

### ISSUE THREAD

**Issue by vasilakisfil** [ByteHeathen/libsip#12]
Hi, not a real issue but more curiosity: is that library focused on client-side SIP or on server side SIP as well ? When I say server I mean proxy,b2bua, registrar, redirect server etc.

For instance, the RegistrationManager is client-focused.

**Comment by bytebuddha** [comment]
Eventually i would like it to work for both. The SipMessage data structure can be used for both.

The client module represents client side sip client , eventually i plan to add a server module that  would have helper structs for the server side of the protocol

**Comment by KalitaAlexey** [comment]
I have REGISTER (without password), SUBSCRIBE (just 200 OK) and calls (p2p and with server as proxy).

**Comment by vasilakisfil** [comment]
ah cool thanks!
