### ISSUE TITLE
Add support for parsing sips URI

### ISSUE THREAD

**Issue by FallingSnow** [ByteHeathen/libsip#27]
`INVITE sips:user:pass@127.0.0.1 SIP/2.0\r\n\r\n66666` does not parse, but `INVITE sip:user:pass@127.0.0.1 SIP/2.0\r\n\r\n66666` does.
Notice the missing "s" after sip.
```rust
[src/broadcast.rs:184] &e.errors[0].1 = Nom(
    Tag,
)
```

**Comment by bytebuddha** [comment]
This should have worked it was a bug in the parser that was fixed in  10f6ac6986812e9a77e3b55ca940d892b6ea6efb
